environments:
    - name: prod
      configs:
        endpoints:
            production:
                url: 'http://backend-prod-service:8080/train-operations/v1/'
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: Default
              deploymentVhost : prod.gw.apim.com
