name: Dev Deployment
on:
  pull_request_target:
    branches:
      - dev
    types:
      - closed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download APICTL
        run: |
          mkdir -p tools
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.3.0/apictl-4.3.0-linux-amd64.tar.gz
          tar -xzvf apictl-4.3.0-linux-amd64.tar.gz
          mv apictl tools/
      - name: Setup Hosts
        run: sudo echo "${HOST_ENTRY}" | sudo tee -a /etc/hosts
        env:
          HOST_ENTRY: ${{ secrets.HOST_ENTRY }}
      - name: Setup API Controller Configurations
        run: |
          mkdir -p $HOME/.wso2apictl
          echo "$CTL_CONFIG" | sed 's/, /\n  /g' >> $HOME/.wso2apictl/main_config.yaml
          cat $HOME/.wso2apictl/main_config.yaml
          mkdir -p $HOME/.wso2apictl.local
          echo "$CTL_KEYS" | sed 's/, /\n  /g' >> $HOME/.wso2apictl.local/keys.json
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        env:
          CTL_CONFIG: ${{ secrets.CTL_CONFIG }}
          CTL_KEYS: ${{ secrets.CTL_KEYS }}
      - name: Login to Dev Environment
        shell: sh
        run: |
          tools/apictl/apictl login dev -u ${{ secrets.DEV_USERNAME }} -p ${{ secrets.DEV_PASSWORD }} --insecure
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
      - name: Checkout API Code
        uses: actions/checkout@v3
        with:
          repository: gogo-transit/train-api
          ref: dev
          fetch-depth: "0"
          path: dev
      - name: Deploy API to Dev Environment
        shell: sh
        run: |
          wget https://github.com/gogo-transit/train-api/releases/download/latest/TrainStationApi-1.0.0.zip
          tools/apictl/apictl import api -f TrainStationApi-1.0.0.zip -e dev --update --preserve-provider=false --params dev/TrainStationApi/1.0.0/params.yaml --insecure
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
      - name: Logout to Dev Environment
        shell: sh
        run: |
          tools/apictl/apictl logout dev --insecure
        if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
